image: nateateteen/zdartpod:full

tasks:
  - name: Install Dart Dependencies
    init: |
      dart pub get

vscode:
  extensions:
    - dart-code.dart-code
    - DavidAnson.vscode-markdownlint
    - editorconfig.editorconfig
    - tamasfe.even-better-toml
