name: Pull Request Labeler
on:
  # https://github.com/actions/labeler?tab=readme-ov-file#notes-regarding-pull_request_target-event
  # switch pull_request_target to pull_request temporarily when making an update to the labeler
  # pull_request:
  pull_request_target:


jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/labeler@v5
        with:
          sync-labels: true
