name: Test on macOS

# Run only one unique workflow at a time on a pr
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name  }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

jobs:
  test-cmd:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: uname
        run: uname -a

      - name: test command
        run: |
          which install

          install --help
